/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/2023-annual-summary': RouteRecordInfo<'/posts/2023-annual-summary', '/posts/2023-annual-summary', Record<never, never>, Record<never, never>>,
    '/posts/Add-umami-analytics-for-my-site': RouteRecordInfo<'/posts/Add-umami-analytics-for-my-site', '/posts/Add-umami-analytics-for-my-site', Record<never, never>, Record<never, never>>,
    '/posts/Apple-Music-Experience': RouteRecordInfo<'/posts/Apple-Music-Experience', '/posts/Apple-Music-Experience', Record<never, never>, Record<never, never>>,
    '/posts/Bitwarden-experience': RouteRecordInfo<'/posts/Bitwarden-experience', '/posts/Bitwarden-experience', Record<never, never>, Record<never, never>>,
    '/posts/Boost-HUAWEI-but-tread-Xiaomi-What-Xiaomi-do-wrong': RouteRecordInfo<'/posts/Boost-HUAWEI-but-tread-Xiaomi-What-Xiaomi-do-wrong', '/posts/Boost-HUAWEI-but-tread-Xiaomi-What-Xiaomi-do-wrong', Record<never, never>, Record<never, never>>,
    '/posts/Build-a-fast-links-page': RouteRecordInfo<'/posts/Build-a-fast-links-page', '/posts/Build-a-fast-links-page', Record<never, never>, Record<never, never>>,
    '/posts/Create-a-simple-bridge-network': RouteRecordInfo<'/posts/Create-a-simple-bridge-network', '/posts/Create-a-simple-bridge-network', Record<never, never>, Record<never, never>>,
    '/posts/Evolution-X-OS-Ten': RouteRecordInfo<'/posts/Evolution-X-OS-Ten', '/posts/Evolution-X-OS-Ten', Record<never, never>, Record<never, never>>,
    '/posts/fix-lenovo-laptop-from-relative': RouteRecordInfo<'/posts/fix-lenovo-laptop-from-relative', '/posts/fix-lenovo-laptop-from-relative', Record<never, never>, Record<never, never>>,
    '/posts/Flash-third-party-firmware-for-Redmi-AX5-router': RouteRecordInfo<'/posts/Flash-third-party-firmware-for-Redmi-AX5-router', '/posts/Flash-third-party-firmware-for-Redmi-AX5-router', Record<never, never>, Record<never, never>>,
    '/posts/Get-started-with-MI-Band-3-NFC': RouteRecordInfo<'/posts/Get-started-with-MI-Band-3-NFC', '/posts/Get-started-with-MI-Band-3-NFC', Record<never, never>, Record<never, never>>,
    '/posts/Get-started-with-Redmi-Watch': RouteRecordInfo<'/posts/Get-started-with-Redmi-Watch', '/posts/Get-started-with-Redmi-Watch', Record<never, never>, Record<never, never>>,
    '/posts/hello-world': RouteRecordInfo<'/posts/hello-world', '/posts/hello-world', Record<never, never>, Record<never, never>>,
    '/posts/Ideas-of-old-seewo': RouteRecordInfo<'/posts/Ideas-of-old-seewo', '/posts/Ideas-of-old-seewo', Record<never, never>, Record<never, never>>,
    '/posts/Lenovo-Yangtian-S550-Experience': RouteRecordInfo<'/posts/Lenovo-Yangtian-S550-Experience', '/posts/Lenovo-Yangtian-S550-Experience', Record<never, never>, Record<never, never>>,
    '/posts/Move-to-Artalk-comment-system': RouteRecordInfo<'/posts/Move-to-Artalk-comment-system', '/posts/Move-to-Artalk-comment-system', Record<never, never>, Record<never, never>>,
    '/posts/Move-to-CloudFlare-Pages': RouteRecordInfo<'/posts/Move-to-CloudFlare-Pages', '/posts/Move-to-CloudFlare-Pages', Record<never, never>, Record<never, never>>,
    '/posts/My-laptop-upgrade-journey': RouteRecordInfo<'/posts/My-laptop-upgrade-journey', '/posts/My-laptop-upgrade-journey', Record<never, never>, Record<never, never>>,
    '/posts/rebuild-my-blog-with-valaxy': RouteRecordInfo<'/posts/rebuild-my-blog-with-valaxy', '/posts/rebuild-my-blog-with-valaxy', Record<never, never>, Record<never, never>>,
    '/posts/Redmi-4-Prime-Experience-Nowadays': RouteRecordInfo<'/posts/Redmi-4-Prime-Experience-Nowadays', '/posts/Redmi-4-Prime-Experience-Nowadays', Record<never, never>, Record<never, never>>,
    '/posts/Redmi-7-personal-experience': RouteRecordInfo<'/posts/Redmi-7-personal-experience', '/posts/Redmi-7-personal-experience', Record<never, never>, Record<never, never>>,
    '/posts/Redmi-K30-custom-guide': RouteRecordInfo<'/posts/Redmi-K30-custom-guide', '/posts/Redmi-K30-custom-guide', Record<never, never>, Record<never, never>>,
    '/posts/Refurbishing-Dell-Inspiron-N4050': RouteRecordInfo<'/posts/Refurbishing-Dell-Inspiron-N4050', '/posts/Refurbishing-Dell-Inspiron-N4050', Record<never, never>, Record<never, never>>,
    '/posts/School-blackouts': RouteRecordInfo<'/posts/School-blackouts', '/posts/School-blackouts', Record<never, never>, Record<never, never>>,
    '/posts/start-using-hexo-mdx-theme': RouteRecordInfo<'/posts/start-using-hexo-mdx-theme', '/posts/start-using-hexo-mdx-theme', Record<never, never>, Record<never, never>>,
    '/posts/Talk-about-rebuild-with-Bulma-and-UnoCSS': RouteRecordInfo<'/posts/Talk-about-rebuild-with-Bulma-and-UnoCSS', '/posts/Talk-about-rebuild-with-Bulma-and-UnoCSS', Record<never, never>, Record<never, never>>,
    '/posts/Talk-about-the-optimization-I-did': RouteRecordInfo<'/posts/Talk-about-the-optimization-I-did', '/posts/Talk-about-the-optimization-I-did', Record<never, never>, Record<never, never>>,
    '/posts/Trying-Android-13-on-my-phone': RouteRecordInfo<'/posts/Trying-Android-13-on-my-phone', '/posts/Trying-Android-13-on-my-phone', Record<never, never>, Record<never, never>>,
    '/posts/USB-Burning-a-tvbox': RouteRecordInfo<'/posts/USB-Burning-a-tvbox', '/posts/USB-Burning-a-tvbox', Record<never, never>, Record<never, never>>,
    '/posts/Use-bulma-css-to-write-friends-link': RouteRecordInfo<'/posts/Use-bulma-css-to-write-friends-link', '/posts/Use-bulma-css-to-write-friends-link', Record<never, never>, Record<never, never>>,
    '/posts/What-I-do-while-I-suspension-of-schooling': RouteRecordInfo<'/posts/What-I-do-while-I-suspension-of-schooling', '/posts/What-I-do-while-I-suspension-of-schooling', Record<never, never>, Record<never, never>>,
    '/posts/Why-I-didnt-join-travellings': RouteRecordInfo<'/posts/Why-I-didnt-join-travellings', '/posts/Why-I-didnt-join-travellings', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
